# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Get Addon Version
      id: version
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: 'src/main/resources/addon.json'
          prop_path: 'version'
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{steps.version.outputs.prop}}
        release_name: Transporter Addon ${{steps.version.outputs.prop}}
        body: |
          Klik under for at hente dette release
        draft: false
        prerelease: false
    
    - name: Copy Artifact 
      run: mv build/libs/transporter-0.0.jar build/libs/transporter-v${{steps.version.outputs.prop}}.jar

    - name: Delete Old Artifact 
      run: rm -f build/libs/transporter-0.0.jar
      
    - name: Upload Artifact To Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/libs/transporter-v${{steps.version.outputs.prop}}.jar
        asset_name: transporter-v${{steps.version.outputs.prop}}.jar
        asset_content_type: application/jar

    - name: Upload Artifact To Workflow
      uses: actions/upload-artifact@v1
      with:
        name: Transporter Addon
        path: build/libs/transporter-v${{steps.version.outputs.prop}}.jar

